name: Smoke Test

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ta-lib-everywhere
        run: |
          python -m pip install --upgrade pip
          pip install ta-lib-everywhere
      - name: Import talib
        run: python -c "import talib"
